https://docs.scipy.org/doc/scipy/reference/sparse.html 

In [2]:
import numpy as np
from scipy import sparse

In [9]:
A = np.array([[1, 0, 0, 3, 0, 0], [0, 0, 0, 0, 0, 0], 
              [0, 0, 0, 0, 0, 0], [2, 0, 0, 8, 0, 0]], dtype=np.int64)
A

array([[1, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [2, 0, 0, 8, 0, 0]])

In [10]:
B = sparse.csr_matrix(A) 
print(B)

  (0, 0)	1
  (0, 3)	3
  (3, 0)	2
  (3, 3)	8


In [11]:
print(B.indptr)
print(B.indices)
print(B.data)

[0 2 2 2 4]
[0 3 0 3]
[1 3 2 8]


In [ ]:
rows, cols = B.nonzero()
print(rows)
print(cols)

[0 0 1 2 2 3 3]
[0 3 2 1 5 0 3]


In [ ]:
print(B.data)

(array([0, 0, 1, 2, 2, 3, 3], dtype=int32), array([0, 3, 2, 1, 5, 0, 3], dtype=int32))
[ 1  3  7 -1  9  2  8]


In [ ]:
B.todense()

matrix([[ 1,  0,  0,  3,  0,  0],
        [ 0,  0,  7,  0,  0,  0],
        [ 0, -1,  0,  0,  0,  9],
        [ 2,  0,  0,  8,  0,  0]], dtype=int64)

In [ ]:
np.count_nonzero(A)

7

In [ ]:
A.size   # num_rows * num_cols

24

In [ ]:
sparsity = 1 - np.count_nonzero(A) / A.size
sparsity

0.7083333333333333

In [ ]:
C = sparse.csc_matrix(A)
print(C)

  (0, 0)	1
  (3, 0)	2
  (2, 1)	-1
  (1, 2)	7
  (0, 3)	3
  (3, 3)	8
  (2, 5)	9


In [ ]:
print(C.indptr)
print(C.indices)
print(C.data)

[0 2 3 4 6 6 7]
[0 3 2 1 0 3 2]
[ 1  2 -1  7  3  8  9]


In [ ]:
print(A)

[[ 1  0  0  3  0  0]
 [ 0  0  7  0  0  0]
 [ 0 -1  0  0  0  9]
 [ 2  0  0  8  0  0]]


In [ ]:
D = sparse.coo_matrix(A, dtype=np.int8)
print(D)   # ijv format - triplet format

  (0, 0)	1
  (0, 3)	3
  (1, 2)	7
  (2, 1)	-1
  (2, 5)	9
  (3, 0)	2
  (3, 3)	8


In [ ]:
D = sparse.coo_matrix(A)
print(D)   

  (0, 0)	1
  (0, 3)	3
  (1, 2)	7
  (2, 1)	-1
  (2, 5)	9
  (3, 0)	2
  (3, 3)	8


In [ ]:
print(D.row)
print(D.col)
print(D.data)


[0 0 1 2 2 3 3]
[0 3 2 1 5 0 3]
[ 1  3  7 -1  9  2  8]


In [ ]:
E = sparse.dok_matrix(A)
print(E)
E.items()

  (0, 0)	1
  (0, 3)	3
  (1, 2)	7
  (2, 1)	-1
  (2, 5)	9
  (3, 0)	2
  (3, 3)	8


dict_items([((0, 0), 1), ((0, 3), 3), ((1, 2), 7), ((2, 1), -1), ((2, 5), 9), ((3, 0), 2), ((3, 3), 8)])